name: ARM Template Deploy Workflow

on:
  push:
    branches: ['master']
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Create Resource Group
        run: az group create --name DeployARM --location eastus

      - name: Deploy ARM Template
        run: az deployment group create --resource-group DeployARM --template-file template.json

  destroy:
    runs-on: ubuntu-latest
    needs: deploy
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Delete Resource Group
        run: az group delete --name DeployARM --yes --no-wait
